name = "ElementaryPDESolutions"
uuid = "88a69b33-da0f-4502-8c8c-d680cf4d883b"
authors = ["Thomas G. Anderson", "Luiz M. Faria"]
version = "0.3.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[weakdeps]
FixedPolynomials = "3dd14ad9-0029-526e-86e9-8aa0bdd2ab0d"
DynamicPolynomials = "7c1d4256-1411-5781-91ec-d7bc3513ac07"

[extensions]
ElementaryPDESolutionsFixedPolynomialsExt = ["FixedPolynomials", "DynamicPolynomials"]

[compat]
FixedPolynomials = "0.4"
DynamicPolynomials = "0.3"
LinearAlgebra = "1"
julia = "1.6"
